### ISSUE TITLE
Kind of confused about the dataset columns

### ISSUE THREAD

**Issue by josiehong** [woshixuhao/Retention-Time-Prediction-for-Chromatographic-Enantioseparation#1]
Thanks for sharing the dataset and the codes! 

I noticed that the y-labels are calculated by two columns, RT multiplies Speed, from `All_column_charity.csv`. Does the 'RT' mean retention time? What is the meaning of RT multiplies Speed? Thanks. 

Best,
Josie

**Comment by woshixuhao** [comment]
Thanks for your interest in our work! RT is the retention time. As dicussed in our paper, according to the chromatographic process equation, there exists an inverse proportional relationship between the retention time and flow ratio. Therefore, we predict RT*v to incorpate the influence of the flow ratio. Of course, you can also put the v into the input and predict only RT, but the precision of the model will decrease to some extent.

**Comment by josiehong** [comment]
Okay. Thank you!
